services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - APP_KEY=${APP_KEY:-XXXXXXXXX}
      - APP_URL=${APP_URL:-http://localhost:6875}
      - DB_HOST=${DB_HOST:-bookstack_db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USERNAME=${DB_USER:-bookstack}
      - DB_PASSWORD=${DB_PASSWORD:-yourpassword}
      - DB_DATABASE=${DB_DATABASE:-bookstackapp}
    volumes:
      - bookstack_app_data:/config
    expose:
      - "80"
    restart: unless-stopped
    depends_on:
      - bookstack_db
    networks:
      - bookstack

  bookstack_db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: bookstack_db
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-yourpassword}
      - TZ=${TZ:-Asia/Dhaka}
      - MYSQL_DATABASE=${DB_DATABASE:-bookstackapp}
      - MYSQL_USER=${DB_USER:-bookstack}
      - MYSQL_PASSWORD=${DB_PASSWORD:-yourpassword}
    volumes:
      - bookstack_db_data:/config
    restart: unless-stopped
    networks:
      - bookstack
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  bookstack_app_data:
  bookstack_db_data:

networks:
  bookstack:
